services:
  fastapi-app:
    build: .
    container_name: churn-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn scripts.main:app --host 0.0.0.0 --port 8000 --reload